### ISSUE TITLE
The readme doesn't provide enough examples

### ISSUE THREAD

**Issue by sole** [mozbrick/brick-layout#6]
I had to go to [the demo](http://mozbrick.github.io/brick-layout/) and then view the source and try to _deduct_ how the component works because just 'using it' resulted in nothing being shown.

Idea: insist in the README that `brick-layout` needs some height to show something:

``` css
brick-layout {
  height: 100%;
}
```
